## De la imagen ya creada ud02

# /usr/local
# wget https://apache.root.lu/hive/hive-2.3.9/apache-hive-2.3.9-bin.tar.gz
# descomprimir: tar -zxvf apache-hive-2.3.9-bin.tar.gz
# rm apache-hive-2.3.9-bin.tar.gz
# ln -s apache-hive-2.3.9-bin hivej
# chown hadoop:hadoop -R apache-hive-2.3.9-bin  hive

